//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Rira.Todo.Domain.Shared.Localization
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rira.Todo.Domain.Shared.Localization.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError
        {
            get
            {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string InternalServerErrorOccured
        {
            get
            {
                return ResourceManager.GetString("InternalServerErrorOccured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to InvalidRequest.
        /// </summary>
        public static string InvalidRequest
        {
            get
            {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No entities found..
        /// </summary>
        public static string NotFoundEntities
        {
            get
            {
                return ResourceManager.GetString("NotFoundEntities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity with ID {Id} not found..
        /// </summary>
        public static string NotFoundEntity
        {
            get
            {
                return ResourceManager.GetString("NotFoundEntity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No response was received from the server.
        /// </summary>
        public static string ServerNoResponse
        {
            get
            {
                return ResourceManager.GetString("ServerNoResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnsupportedMediaTypeMessage {0} {1}.
        /// </summary>
        public static string UnsupportedMediaTypeMessage
        {
            get
            {
                return ResourceManager.GetString("UnsupportedMediaTypeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string ValidationError
        {
            get
            {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
